version: Build-{build}
image: Visual Studio 2017

environment:
  MsBuildVerbosity: minimal

configuration: Release

before_build:
- ps: >-
    dotnet restore "$env:APPVEYOR_BUILD_FOLDER\NetChris.Core.sln"

    appveyor DownloadFile https://gitlab.com/NetChris/NetChris.BuildTools.Public/raw/master/Scripts/VersionCSPROJ/VersionCSPROJ.ps1

    .\VersionCSPROJ.ps1 -BuildNumber $env:APPVEYOR_BUILD_NUMBER -csproj "$env:APPVEYOR_BUILD_FOLDER\NetChris.Core\NetChris.Core.csproj" -commit $env:APPVEYOR_REPO_COMMIT

    appveyor DownloadFile https://gitlab.com/NetChris/NetChris.BuildTools.Public/raw/master/Scripts/AppVeyor/BuildRename.ps1

    .\BuildRename.ps1

build_script:
- ps: >-
    dotnet build --configuration ${env:CONFIGURATION} --verbosity ${env:MsBuildVerbosity} "${env:APPVEYOR_BUILD_FOLDER}\NetChris.Core.sln"

test_script:
- ps: >-
    dotnet test "${env:APPVEYOR_BUILD_FOLDER}\NetChris.Core.UnitTests\NetChris.Core.UnitTests.csproj"

after_build:
- ps: >-
    $env:PackFolder = "${env:APPVEYOR_BUILD_FOLDER}\pack\NetChris.Core\"

    dotnet pack --configuration ${env:CONFIGURATION} --verbosity ${env:MsBuildVerbosity} --output "$env:PackFolder" "${env:APPVEYOR_BUILD_FOLDER}\NetChris.Core\NetChris.Core.csproj"

artifacts:
- path: '**\NetChris.Core.*.*.*.nupkg'
  name: NetChris.Core.nupkg

deploy:
- provider: Environment
  name: myget.org/F/netchris-dev-public
- provider: Environment
  name: nuggetboy.nuget.org
  on:
    appveyor_repo_tag: true
