# TODO - Establish as standard and place in GitHub composite action
name: Build, test, pack, push to NuGet registry

on:
  workflow_call:
    inputs:
      nuget_version:
        description: 'NuGet Version for the package'
        required: true
        type: string
      dotnet_assembly_version:
        description: '.NET Assembly Version'
        required: true
        type: string
      nuget_source:
        description: 'Package source (URL, UNC/folder path or package source name) to use.'
        required: false
        # TODO - Document that this is the default
        default: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json 
        type: string
    secrets:
      nuget_api_key:
        # TODO - Is there a way to default this to ${{ secrets.GITHUB_TOKEN }}?
        required: true

jobs:
  build-test-pack-push:
    runs-on: ubuntu-latest
    name: Build, Test, Pack, Push
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
      - name: Build
        run: dotnet build --configuration Release
      - name: Test
        run: dotnet test --configuration Release --no-build
      - name: Paranoid NuGet package clean
        # For convenience we push *.nupkg later, so make sure the output folder is wiped, a paranoid move in case we re-use a runner?
        run: rm -rf ./nupkgs
      - name: Pack
        run: dotnet pack --configuration Release /p:PackageVersion=${{ inputs.nuget_version }} /p:Version=${{ inputs.dotnet_assembly_version }} --output ./nupkgs
      - name: Push
        run: dotnet nuget push ./nupkgs/*.nupkg --source ${{ inputs.nuget_source }} --api-key ${{ secrets.nuget_api_key }}
