name: Pre-Release

on:
  release:
    types: [prereleased]

jobs:
  push:
    # TODO - Document this requirement
    permissions:
      contents: read
      packages: write
    # TODO - SHA
    uses: NetChris/workflows/.github/workflows/dotnet/build-test-pack-push/pre-release.yml@1-simple-dotnet-build-test-pack-push
    # TODO - Document this requirement 
    secrets: inherit
