# TODO - Establish as standard and place in GitHub composite action
name: Build, Test, Pack, and push to Pre-Release registry

# TODO - One job to push to GH registry
# TODO - One job to push to inttest NuGet
# TODO - One job to push to NuGet.org
# TODO - Commonize ^^^^

on:
  release:
    types: [prereleased]

jobs:
  derive_semver:
    runs-on: ubuntu-latest
    outputs:
      nuget_version: ${{ steps.parse.outputs.nuget_version }}
      dotnet_assembly_version: ${{ steps.parse.outputs.dotnet_assembly_version }}
    steps:
      - name: Derive SemVer
        id: parse
        # TODO - Use SHA
        uses: NetChris/parse-semver@11-output-nuget-microsoft-versions
  build-test-pack-push-github:
    needs: derive_semver
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-test-pack-push.yml
    with:
      nuget_version: ${{ needs.derive_semver.outputs.nuget_version }}
      dotnet_assembly_version: ${{ needs.derive_semver.outputs.dotnet_assembly_version }}
      # We default to pushing to the organizational feed, so no value for nuget_source
    secrets:
      nuget_api_key: ${{ secrets.GITHUB_TOKEN }}
  build-test-pack-push-nugettest:
    name: Build, Test, Pack, and push to int.nugettest.org
    needs: derive_semver
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-test-pack-push.yml
    with:
      nuget_version: ${{ needs.derive_semver.outputs.nuget_version }}
      dotnet_assembly_version: ${{ needs.derive_semver.outputs.dotnet_assembly_version }}
      nuget_source: https://apiint.nugettest.org/v3/index.json
    secrets:
      nuget_api_key: ${{ secrets.NC_INT_NUGETTEST_ORG_API_KEY }}
