# TODO - Establish as standard and place in GitHub composite action
name: Build, Test, Pack, and push to Pre-Release registry

# TODO - One job to push to GH registry
# TODO - One job to push to inttest NuGet
# TODO - One job to push to NuGet.org
# TODO - Commonize ^^^^

on:
  release:
    types: [prereleased]

jobs:
  publish_pre_release:
    runs-on: ubuntu-latest
    name: TODO
    steps:
      - name: Build
        run: echo XXXX
