name: Release - NuGet.org

on:
  release:
    types: [released]

jobs:
  nuget-oidc:
    name: NuGet login (OIDC → temp API key)
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # enable GitHub OIDC token issuance for this job
    outputs:
      nuget_api_key: ${{ steps.secretworkaround.outputs.NUGET_API_KEY }}
    steps:
      - uses: NuGet/login@v1
        id: login
        with:
          user: ChrisSimmons
      - name: Save Secret
        id: secretworkaround
        run: echo "NUGET_API_KEY=${{ steps.login.outputs.NUGET_API_KEY }}" >> "$GITHUB_OUTPUT"
  push:
    needs:
      - nuget-oidc
    permissions:
      checks: write
      contents: read
      packages: write
    uses: NetChris/workflows/.github/workflows/release-nuget-org.yml@nuget-trusted-publishing
    secrets: 
      nuget_api_key: ${{ needs.nuget-oidc.outputs.nuget_api_key }}
