# TODO - How to share this
name: Pre-Release

# TODO - Can we pack once and push multiple times?

on:
  release:
    types: [prereleased]

jobs:
  parse_semver:
    name: Parse SemVer
    runs-on: ubuntu-latest
    outputs:
      nuget_version: ${{ steps.parse_semver_action.outputs.nuget_version }}
      dotnet_assembly_version: ${{ steps.parse_semver_action.outputs.dotnet_assembly_version }}
    steps:
      - id: parse_semver_action
        uses: NetChris/parse-semver@fdf7c91e3c241d139205239b3a48d3e0a530f64c
  build-test-pack-push-github:
    name: GitHub NuGet registry
    needs: parse_semver
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/called-build-test-pack-push.yml
    with:
      nuget_version: ${{ needs.parse_semver.outputs.nuget_version }}
      dotnet_assembly_version: ${{ needs.parse_semver.outputs.dotnet_assembly_version }}
      # We default to pushing to the organizational feed, so no value for nuget_source
    secrets:
      nuget_api_key: ${{ secrets.GITHUB_TOKEN }}
  build-test-pack-push-nugettest:
    name: int.nugettest.org
    needs: parse_semver
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/called-build-test-pack-push.yml
    with:
      nuget_version: ${{ needs.parse_semver.outputs.nuget_version }}
      dotnet_assembly_version: ${{ needs.parse_semver.outputs.dotnet_assembly_version }}
      nuget_source: ${{ vars.NC_INT_NUGETTEST_ORG_API_SOURCE_URL }}
    secrets:
      nuget_api_key: ${{ secrets.NC_INT_NUGETTEST_ORG_API_KEY }}
  build-test-pack-push-nugetorg:
    name: nuget.org
    needs: parse_semver
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/called-build-test-pack-push.yml
    with:
      nuget_version: ${{ needs.parse_semver.outputs.nuget_version }}
      dotnet_assembly_version: ${{ needs.parse_semver.outputs.dotnet_assembly_version }}
      nuget_source: ${{ vars.NC_NUGET_ORG_API_SOURCE_URL }}
    secrets:
      nuget_api_key: ${{ secrets.NC_NUGET_ORG_API_KEY }}
