name: Release

on:
  release:
    types: [released]

jobs:
  push:
    permissions:
      contents: read
      packages: write
    uses: NetChris/workflows/.github/workflows/release-dotnet-build-test-pack-push-default.yml@v0.0
    secrets: inherit
