name: Push

on: [push]

jobs:
  push:
    permissions:
      checks: write
      contents: read
      packages: write
    uses: NetChris/workflows/.github/workflows/push-dotnet-build-test-pack-push-default.yml@test-results
