name: Push

on: [push]

jobs:
  push:
    # TODO - Document this requirement
    permissions:
      contents: read
      packages: write
    # TODO - SHA
    uses: NetChris/workflows/.github/workflows/dotnet/build-test-pack-push/push.yml@1-simple-dotnet-build-test-pack-push
