name: Build, Test, Pack, and push to GitHub NuGet registry

on: [push]

# TODO - Is this something we can put in a shared action?

jobs:
  derive_semver:
    runs-on: ubuntu-latest
    outputs:
      nuget_version: ${{ steps.parse.outputs.nuget_version }}
      dotnet_assembly_version: ${{ steps.parse.outputs.dotnet_assembly_version }}
    steps:
      - name: Derive SemVer
        id: parse
        uses: NetChris/parse-semver@fdf7c91e3c241d139205239b3a48d3e0a530f64c
  build-test-pack-push:
    needs: derive_semver
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-test-pack-push.yml
    with:
      # The version here is long but it ensures each push is unique.
      nuget_version: ${{ needs.derive_semver.outputs.nuget_version }}-${{ github.run_number }}-${{ github.run_attempt }}-${{ github.run_id }}
      dotnet_assembly_version: ${{ needs.derive_semver.outputs.dotnet_assembly_version }}
      # We default to pushing to the organizational feed, so no value for nuget_source
    secrets:
      nuget_api_key: ${{ secrets.GITHUB_TOKEN }}
